#! /bin/sh

# TODO Needs less cruft
LDFLAGS="-I/usr/lib/clang/2.8/include -I/usr/include/ "
LDFLAGS=$LDFLAGS`pkg-config --cflags --libs jack`
LDFLAGS=$LDFLAGS`pkg-config --cflags --libs fftw3`
LDFLAGS=$LDFLAGS`pkg-config --cflags --libs gstreamer-0.10`
LDFLAGS=$LDFLAGS`pkg-config --cflags --libs gstreamer-plugins-base-0.10`

TARGETS_JACK="clang -c $LDFLAGS src/clover-jack.cpp -o bin/clover-jack.o"
TARGETS_GST="clang -c $LDFLAGS src/clover-gst.cpp -o bin/clover-gst.o"
TARGET_OBJS="bin/*.o"
TARGETS="clang $LDFLAGS src/clover.cpp $TARGET_OBJS -o bin/clover"

PREFIX="/usr/bin/clover"
INSTALL="mv bin/clover $PREFIX"
CLEAN="rm bin/*"
UNINSTALL="sudo rm $PREFIX"
CONTENT="SHELL=/bin/sh \nall: \n\t$TARGETS_JACK && $TARGETS_GST && $TARGETS \n\ninstall: \n\t$INSTALL \n\nclean:\n\t $CLEAN \n\nuninstall:\n\t $UNINSTALL"

# Refresh Makefile
rm Makefile
echo $CONTENT >> Makefile