#! /bin/sh
LDFLAGS="-I/usr/lib/clang/2.8/include -I/usr/include/ "
LDFLAGS=$LDFLAGS`pkg-config --cflags --libs jack`
LDFLAGS=$LDFLAGS`pkg-config --cflags --libs fftw3`
LDFLAGS=$LDFLAGS`pkg-config --cflags --libs gstreamer-0.10`

TARGETS="clang $LDFLAGS src/warlock.cpp -o bin/warlock"

# Refresh Makefile
rm Makefile
cat >> Makefile << EOF
SHELL=/bin/sh
all: $TARGETS
EOF